export const SWITCH_FAVORITE_CONTACTS = 'SWITCH_FAVORITE_CONTACTS';
export const DELETE_CONTACT_FROM_FAVORITE = 'DELETE_CONTACT_FROM_FAVORITE';
export const SET_FAVORITE_CONTACTS = 'SET_FAVORITE_CONTACTS';
export const SET_LOADING_FAVORITE_CONTACTS = 'SET_LOADING_FAVORITE_CONTACTS';
export const SET_SUCCESS_FAVORITE_CONTACTS = 'SET_SUCCESS_FAVORITE_CONTACTS';
export const RESET_FAVORITE_CONTACTS = 'RESET_FAVORITE_CONTACTS';