export const SET_CONTACTS = 'SET_CONTACTS';
export const SET_LOADING_CONTACTS = 'SET_LOADING_CONTACTS';
export const SET_SUCCESS_CONTACTS = 'SET_SUCCESS_CONTACTS';
export const RESET_CONTACTS = 'RESET_SUCCES_CONTACTS';
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT= 'DELETE_CONTACT';