export const SET_GROUP_CONTACTS= 'SET_GROUP_CONTACTS';
export const ADD_GROUP_CONTACT= 'ADD_GROUP_CONTACT';
export const DELETE_GROUP_CONTACT= 'DELETE_GROUP_CONTACT';
export const DELETE_CONTACT_FROM_GROUP= 'DELETE_CONTACT_FROM_GROUP';
export const SET_LOADING_GROUP_CONTACTS = 'SET_LOADING_GROUP_CONTACTS';
export const SET_SUCCESS_GROUP_CONTACTS = 'SET_SUCCESS_GROUP_CONTACTS';
export const RESET_GROUP_CONTACTS = 'RESET_GROUP_CONTACTS';